server:
  port: 10107

fake_data:
  student_names:
    - "宋爱梅"
    - "王志芳"
    - "于光"
    - "贾隽仙"
    - "贾燕青"
    - "刘振杰"
    - "郭卫东"
    - "崔红宇"
    - "马福平"
    - "冯红"
    - "崔敬伟"
    - "穆增志"
    - "谢志威"
    - "吕金起"
    - "韩云庆"
    - "鲁全福"
    - "郭建立"
    - "郝连水"
    - "闫智胜"
  academies:
    - "电气与信息工程学院"
    - "外国语学院"
    - "商学院"
    - "冶金工程学院"
    - "材料学与工程学院"
    - "化学与化工学院"
    - "建筑工程学院"
    - "公共管理与法学院"
  teacher_names:
    - "龙力行"
    - "容飞跃"
    - "秦乐安"
    - "曾成龙"
    - "魏嘉平"
    - "厍俊侠"
    - "赵永"
    - "弓才哲"
    - "江彭泽"
    - "王玉石"
    - "巢子琪"
    - "弘凯"
    - "周修伟"
    - "方文翰"
    - "邓德惠"
    - "田文轩"
    - "徐宜民"
  addresses:
    - "马鞍山人民医院"
    - "马鞍山市妇幼保健医院"
    - "马鞍山市钢城医院"
    - "马鞍山市第四人民医院"
  reason:
    - "急性胃炎需要治疗"
    - "肚子疼痛需要治理"
    - "阑尾炎需要治疗"
    - "痔疮犯了，要去治治"
    - "皮肤湿疹"
  idBegin: 217054000
  idEnd: 229064222